# -*- coding: utf-8 -*-
"""EDA3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wH5-l5oBCUKgUE4g7vF1VYDnE5Ogvc2G

# Warm-up: visual investigation

Run the code below and add a your answers to the questions below to the text box under the output.

Each of the following visualizations compares body mass across penguin species.

1. For each chart, describe what it does well, and what it could improve upon. Consider things like statistical measures, visual appeal, informativeness, etc.

2. Lastly, come up with an informative and appealing title for each chart.
"""

import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt

penguins = sns.load_dataset('penguins')

fig, axes = plt.subplots(1, 4, figsize=(20, 5))

# Plot A: Body Mass Distribution (Histogram + KDE)
sns.histplot(data=penguins,
             x='body_mass_g',
             bins=20, alpha=0.6,
             hue='species',
             palette='magma',
             kde=True,
             ax=axes[0])  # Use the first subplot
axes[0].set_title('Chart A')
axes[0].set_xlabel('Body Mass (g)')
axes[0].set_ylabel('Frequency')

# Plot B: Body Mass Distribution (Boxplot)
sns.boxplot(data=penguins,
            x='body_mass_g',
            hue='species',
            palette='magma',
            ax=axes[1])  # Use the second subplot
axes[1].set_title('Chart B')
axes[1].set_xlabel('Body Mass (g)')

# Plot C: Body Mass Distribution (Violin Plot)
sns.violinplot(data=penguins,
               y='species',
               x='body_mass_g',
               hue='species',
               palette='magma',
               density_norm ='count',
               ax=axes[2])  # Use the third subplot
axes[2].set_title('Chart C')
axes[2].set_xlabel('Body Mass (g)')
axes[2].set_ylabel(None)  # No label for y-axis

# Plot D: Body Mass Distribution (Barplot with pivot table)
sns.barplot(data=penguins,
            y='species',
            x='body_mass_g',
            hue='species',
            palette='magma',
            ax=axes[3])  # Use the fourth subplot
axes[3].set_title('Chart D')
axes[3].set_xlabel('Body Mass (g)')
axes[3].set_ylabel(None)  # No label for y-axis

"""1. critique each chart

A:

B:

C:

D:


2. update titles

A:

B:

C:

D:

#Plotting libraries

plot
"""

penguins.plot(kind = "scatter",
              x= "flipper_length_mm",
              y = "body_mass_g")

"""matplotlib"""

plt.scatter(penguins["flipper_length_mm"],penguins["body_mass_g"])

"""seaborn"""

sns.scatterplot(data = penguins,
                x = "flipper_length_mm",
                y = "body_mass_g")

"""plotnine"""

from plotnine import ggplot, geom_point, aes

(ggplot(penguins, aes("flipper_length_mm", "body_mass_g"))
    + geom_point()
)

"""#Visualizations

"""

penguins['body_mass_g'].plot(kind='hist', bins=20,color='indigo', edgecolor='black')

penguins['body_mass_g'].describe()

penguins['species'].value_counts()

sns.countplot(data=penguins,
   x='species',
   color='tab:olive')

plt.title('Barchart: Species Count')
plt.xlabel(None)
plt.ylabel('Count')

sns.scatterplot(data=penguins,
 		    x='bill_length_mm',
    y='bill_depth_mm',
    hue = 'species',
    palette='viridis')
plt.title('Bill Dimensions by Species')
plt.xlabel('Length (mm)')
plt.ylabel('Depth (mm)')

sns.lmplot(data=penguins,
          x='bill_length_mm',
          y='bill_depth_mm',
          hue="species",
          palette='viridis',
          legend=None, height=6)
plt.legend(loc='lower left', ncol=1)

pivot_data = penguins.pivot_table(index='species',
columns='sex',
aggfunc='size',
fill_value=0)

pivot_data.plot(kind='bar', stacked=True,
    color= ['green', 'tab:olive'])

sns.boxplot(data = penguins, x = 'island',y ='body_mass_g',
  hue = 'species', palette = 'crest', linewidth=0.3)

num_penguins = penguins.select_dtypes(include = ['float64', 'int64'])
corr_matrix = num_penguins.corr()
sns.heatmap(corr_matrix, annot=True, cmap='magma', fmt='.2f', cbar=True)

sns.pairplot(penguins, hue='species',palette='magma', dropna=True)

"""#Exercise: choose your chart type

Below are some pairings of features. Decide which chart type and/or summary would be best. Add these to the text box below.

Once you have selected your charts, pick two to create. Opening the slide deck in a new tab may be helpful.

A: island

B: flipper_length_mm

C: flipper_length_mm, bill_length_mm

D: bill_length_mm, island

E: flipper_length_mm, bill_length_mm, island
"""

#chart one

#chart two

"""#to-do

Take a look at PA1 and do Tasks 1-2 before Monday.
"""